// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jqdjfmnmiyfczrgtyisp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpxZGpmbW5taXlmY3pyZ3R5aXNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2NzA4MTUsImV4cCI6MjA3MTI0NjgxNX0.w7gDNlre590swUFGAdr-W9FeEq4DMMVJuc5YKFwOnlM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});